### ISSUE TITLE
Allow changing path used to mount NFS volume

### ISSUE THREAD

**Issue by quinncomendant** [AntonioMeireles/coreos-xhyve#65]
Currently `corectl` mounts the entire `/Users/username` directory on a NFS mount. This exposes the user's entire home directory to coreos. During development and experimentation, this exposes all the user's files to unnecessary risk of file access or deletion. It would be best to allow the user to specify which path should be included in the NFS mount. E.g., I would like to limit access to only `/Users/q/src`.

**Comment by AntonioMeireles** [comment]
@quinncomendant NFS exposure of user's host home dir is now optional (`-H`). OTOH there's nothing that blocks you from feeding the guest with a cloud-config that mounts on it whatever you want from host or elsewhere.  Please reopen if this isn't enough for your use case. Thanks!

**Comment by quinncomendant** [comment]
This is fantastic. Thank you.

I'm not sure how to use cloud-config to mount NFS. Can you post an example?

I'd like to mount `/Users/q/src` instead of `/Users/q`. I've tried the following, but it doesn't work:
- Updated `/etc/exports` to use the path `/Users/q/src` instead of `/Users/q`.
- Modified [this example](https://coreos.com/os/docs/latest/mounting-storage.html#mounting-nfs-exports) to the `units` section of my cloud-config:

``` yaml
- name: rpc-statd.service
  command: start
  enable: true
- name: Users-q-src.mount
  command: start
  content: |
    [Mount]
    What=/Users/q/src
    Where=/Users/q/src
    Type=nfs
```
- I have excluded `-H` when running `corectl run`.
- When I `corectl ssh containerland` I see this error:

```
Failed Units: 2
  Users-q-src.mount
  outter-connectivity-check.service
```
- And although my chosen path is created, it is empty:

```
core@containerLand ~ $ ls -l /Users/q/src
total 0
```
